name: tfe


services:
  frontend:
    build: ./frontend
    volume:
      - ./frontend/dist:/app/dist

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports: 
      - "8080:8080"

#  db:
#    image: postgres
