name: tfe

services:
  frontend:
    build: ./frontend

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports: 
      - "80:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    build: ./db
    expose:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U truii"]
      interval: 1s
      timeout: 1s
      retries: 5

  adminer:
    image: adminer:latest
    ports:
      - "8001:8080"

