name: tfe

services:
  frontend:
    build: ./frontend

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports: 
      - "80:8080"
    depends_on:
      - db

  db:
    build: ./db
    expose:
      - "5432:5432"

  adminer:
    image: adminer:latest
    ports:
      - "8001:8080"

