# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=truii
ENV POSTGRES_PASSWORD=truii
ENV POSTGRES_DB=tfedb

# Expose the PostgreSQL port
EXPOSE 5432


# Start PostgreSQL server when the container launches
CMD ["postgres"]
